### ISSUE TITLE
[Bug] Unable to reach the origin service. 

### ISSUE THREAD

**Issue by KairuByte** [brenner-tobias/addon-cloudflared#38]
**Describe the bug**
When trying to connect through the tunnel, I receive a "too many redirects" response.

**To Reproduce**
Bug happens on initial setup. Have properly authorized on Cloudflare and the DNS record has been properly created.
```additional_hosts: []
external_hostname: host.name.here
tunnel_name: homeassistant
nginxproxymanager: true
log_level: debug
```
(Please note `host.name.here` is not the actual hostname in the config)

**Expected behavior**
Connects to home assistant.

**Screenshots**

**Add-On / Home Assistant Information (please complete the following information):**

- Add-On Version:  0.4.1
- Supervisor Version: supervisor-2022.01.1
- Core Version: core-2022.2.2
- Operating System: Home Assistant OS 7.2
- Devices: rPi4B8GB

**Additional context**
Error is repeated:
```2022-02-06T20:04:36Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=6d96fd0e3cc6c51c-ORD ingressRule=0 originService=http://homeassistant:8123
2022-02-06T20:04:36Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=6d96fd0e9d28c51c-ORD ingressRule=0 originService=http://homeassistant:8123
2022-02-06T20:04:38Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=6d96fd1b5b5ee1ce-ORD ingressRule=0 originService=http://homeassistant:8123
2022-02-06T20:04:38Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=6d96fd1c9c55e1ce-ORD ingressRule=0 originService=http://homeassistant:8123
2022-02-06T20:04:42Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=6d96fd37f9dac51c-ORD ingressRule=0 originService=http://homeassistant:8123
```

**Comment by KairuByte** [comment]
For the record, `http://homeassistant:8123` is not accessible from my network, but `https://hassio:8123` is.

**Comment by brenner-tobias** [comment]
It looks like your config is in an old state. Just to make sure, could you please update it to something like this:

```
external_hostname: host.name.here
tunnel_name: homeassistant
additional_hosts: []
nginx_proxy_manager: true
```

The two things I am missing in your config is 'additional_hosts: []' and the `nginx_proxy_manager` was renamed.

Once you have done that, please do a restart and let me know.

**Comment by KairuByte** [comment]
`additional_hosts` was actually present previously but I apparently forgot to copy it over. I have confirmed the same issue with the below:

```additional_hosts: []
external_hostname: host.hame.here
tunnel_name: homeassistant
nginx_proxy_manager: true
log_level: debug
```

**Comment by brenner-tobias** [comment]
Should be fixed in v0.4.2, can you please check and let me know?

**Comment by elcajon** [comment]
> For the record, `http://homeassistant:8123` is not accessible from my network, but `https://hassio:8123` is.

@brenner-tobias If the bugfix you provided won't fix the problem... I assume the homeassistant docker container expects incoming SSL traffic on 8123 due to [configured SSL ](https://www.home-assistant.io/integrations/http/#ssl_certificate). Maybe we should set the homeassistant ingress service based on `bashio::core.ssl` (true = https or false = http). I would also assume that hostname `homeassistant` is correct (even when OS hostname is changed to `hassio`), as the internal docker hostname is defined as `homeassistant` and (afaik) isn't changeable at all.

**Comment by brenner-tobias** [comment]
Very good point @elcajon, thanks for keeping an eye on these issues :-)
Since I was not sure from the beginning, whether or not the hostname might change, I directly jumped to the conclusion that this must be the cause when I saw that the hassio one was working. Let's see if the fix does change something for @KairuByte, nevertheless I think, we have to answer two questions now:

1. Should we keep the IP or change it back to the (docker) hostname? Which one do we think is "more static"?
2. Do we want to include the SSL option or do we want to state (even more clear than it is right now) in the documentation that the tunnel is only meant to work without any SSL configuration in HA whatsoever. A couple of thoughts:
- SSL is unneeded for the tunnel, since it is a connection within the docker network
- On the other hand, if someone uses a local connection, once he is in his network (e.g. wich the app which can be configured to do exactly that), it might not be a bad idea to set up ssl anyways.

Thoughts?

**Comment by KairuByte** [comment]
So, I can confirm that it does not work, and I think SSL is indeed the cause.

I am using the same hostname internally with SSL enabled. This is to increase the wife acceptance level to "acceptable".

I realize I could disable SSL and still be secure on tunnel based connections, but I would much prefer to keep SSL enabled if possible.

**Comment by brenner-tobias** [comment]
alright, thanks a lot for your input. I will work on a branch later today and incorporate that.

**Comment by brenner-tobias** [comment]
@KairuByte I just released v0.4.3, can you please check if this solves your problem?

**Comment by KairuByte** [comment]
Hrm, oddly I am still getting the same error in the browser, but I am not seeing any information in the logs.

**Comment by KairuByte** [comment]
The cloudflared log is showing nothing after the `INF Connection [GUID] registered connIndex=0 location=ORD` type lines, of which there are four. The exact error is browser specific, for example Chrome on Windows reports a status of `(failed)net::ERR_TOO_MANY_REDIRECTS`.

I can't seem to find a log within Cloudflares dashboard that correlates to tunnel connections, but if there is one I can provide the information from them as well.

**Comment by KairuByte** [comment]
Slight update, it seems swapping SSL to `Flexible` allows most things to connect properly. However I am having a heck of a time getting the companion app to connect.

**Comment by brenner-tobias** [comment]
Glad it is working, though you should really not need to set SSL in Cloudflare to flexible for this. Also, regarding the companion app, I suggest you enter the IP with a "https" at the beginning as the Internal URL. You can either go with the internal IP or with `https://hassio:8123`, both should work fine
