### ISSUE TITLE
Cloudflared not found after update

### ISSUE THREAD

**Issue by computeralex92** [brenner-tobias/addon-cloudflared#387]
### The problem

After updating to the latest update, this error appears 

```-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[23:06:50] INFO: Using Cloudflare Remote Management Tunnel
[23:06:50] INFO: All add-on configuration options except tunnel_token will be ignored.
[23:06:50] INFO: Connecting Cloudflare Tunnel...
./run: line 33: exec: cloudflared: not found
[23:06:50] WARNING: cloudflared crashed, halting add-on
[23:06:50] INFO: cloudflared stoped, restarting...
```

### What version of Cloudflared has the issue?

4.1.3

### What was the last working version of Cloudflared?

4.1.2

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Update to the latest version

**Comment by matthewhadley** [comment]
I am getting the same error after updating to Cloudflared `4.1.3` from `4.1.2`

**Comment by computeralex92** [comment]
It seems that #386 found it’s way to the stable version

**Comment by pippyn** [comment]
Same error here

**Comment by nikoxley** [comment]
Yeah same here too.

**Comment by BrammyS** [comment]
Also experiencing this issue with version 4.1.3

**Comment by brenner-tobias** [comment]
@elcajon are we sure this was fixed upstream?

**Comment by Benne007** [comment]
I am getting the same error after updating to Cloudflared 4.1.3 from 4.1.2

**Comment by przemoc86** [comment]
For me also it's stopped to work. I've reinstalled the add-on and currently new error is shown

` Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[00:28:59] INFO: Checking add-on config...
[00:29:01] INFO: Checking for existing certificate...
[00:29:01] NOTICE: No certificate found
[00:29:01] INFO: Creating new certificate...
[00:29:01] NOTICE: 
[00:29:01] NOTICE: Please follow the Cloudflare Auth-Steps:
[00:29:01] NOTICE: 
/etc/s6-overlay/scripts/cloudflared-config.sh: line 92: cloudflared: command not found
s6-rc: warning: unable to start service init-cloudflared-config: command exited 127
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

**Comment by acseven** [comment]
> For me also it's stopped to work. I've reinstalled the add-on and currently new error is shown
> 
> ```
> Add-on: Cloudflared
>  Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
> -----------------------------------------------------------
>  Add-on version: 4.1.3
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 10.0  (amd64 / qemux86-64)
>  Home Assistant Core: 2023.4.6
>  Home Assistant Supervisor: 2023.04.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> [00:28:59] INFO: Checking add-on config...
> [00:29:01] INFO: Checking for existing certificate...
> [00:29:01] NOTICE: No certificate found
> [00:29:01] INFO: Creating new certificate...
> [00:29:01] NOTICE: 
> [00:29:01] NOTICE: Please follow the Cloudflare Auth-Steps:
> [00:29:01] NOTICE: 
> /etc/s6-overlay/scripts/cloudflared-config.sh: line 92: cloudflared: command not found
> s6-rc: warning: unable to start service init-cloudflared-config: command exited 127
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> ```

I the exact same issue

**Comment by elninosi** [comment]
I also have this issue after updating:
```
/etc/s6-overlay/scripts/cloudflared-config.sh: line 123: cloudflared: command not found
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

**Comment by EDOUNA** [comment]
For me the same.

**Comment by MrPresident2** [comment]
Same thing, after update:

```
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[15:51:03] INFO: Checking add-on config...
[15:51:03] INFO: Checking for existing certificate...
[15:51:03] NOTICE: No certificate found
[15:51:03] INFO: Creating new certificate...
[15:51:03] NOTICE: 
[15:51:03] NOTICE: Please follow the Cloudflare Auth-Steps:
[15:51:03] NOTICE: 
/etc/s6-overlay/scripts/cloudflared-config.sh: line 92: cloudflared: command not found
s6-rc: warning: unable to start service init-cloudflared-config: command exited 127
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

**Comment by SunsetGolfer** [comment]
Same problem here:

-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[01:03:18] INFO: Using Cloudflare Remote Management Tunnel
[01:03:18] INFO: All add-on configuration options except tunnel_token will be ignored.
[01:03:19] INFO: Connecting Cloudflare Tunnel...
./run: line 33: exec: cloudflared: not found
[01:03:19] WARNING: cloudflared crashed, halting add-on
[01:03:19] INFO: cloudflared stoped, restarting...

**Comment by qbaza** [comment]
I have the same problem.

**Comment by bredboye** [comment]
Same issue. Everything was fine before this update. I'll have to make a note of reading issues on GH before I blindly install a broken update.

**Comment by martijn-brant** [comment]
Some issue with new version, I had auto update on but luckily my HA made a backup of the older version. I was able to restore it via the HA backup page in the settings. Now it works again.

**Comment by martijn-brant** [comment]
ping @elcajon @brenner-tobias, you're latest update to this addon is broken. Might want to pull it.

**Comment by brenner-tobias** [comment]
Sorry for this inconvenience, but there seems to be an error with the newest Cloudflared amd build. We thought this was resolved but it looks like it is not.

I just release v4.1.4. which reverts Cloudflared back to the previous version as a temporary fix. Please give the newest version a try and let me know.

**Comment by bredboye** [comment]
It hasn't propagated to my version of the repo in home assistant yet. Hopefully by the time I get home I'll be able to try it out. I did try reburning back to 4.1.2 but I was still having a problem where it would just keep auto refreshing and saying unable to connect.

**Comment by remoteassist** [comment]
Updated to 4.1.4, I am having problem finding how to delete the tunnel on Cloudflare site, does anyone know where it is located. 

```
Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.1.4
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[20:34:42] INFO: Checking add-on config...
[20:34:42] INFO: Checking for existing certificate...
[20:34:42] INFO: Existing certificate found
[20:34:42] INFO: Checking for existing tunnel...
[20:34:42] NOTICE: No tunnel file found
[20:34:42] INFO: Creating new tunnel...
failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
[20:34:42] FATAL: Failed to create tunnel.
    Please check the Cloudflare Zero Trust Dashboard for an existing tunnel with the name homeassistant and delete it:
    Visit https://one.dash.cloudflare.com, then click on Access / Tunnels
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

**Comment by nekerd** [comment]
We love you so much Tobias for providing us the most relevant add-on that Home Assistant has. This is the best way so far to access remote to our HA. Nevertheless, please do not do this again!!!

I recommend to access the your HA using your local url and then go Back to 4.1.2

The 4.1.4 version doesn't work for me.
We love you so much Tobias for providing us the most relevant add-on that Home Assistant has. This is the best way so far to access remote to our HA. Nevertheless, please do not do this again!!!

I recommend to access the your HA using your local url and then go Back to 4.1.2

The 4.1.4 version doesn't work for me.

**Comment by computeralex92** [comment]
I can confirm that the v4.1.4 is fixing the issue for me.
Maybe because I use the remote config & a tunnel token I have no  `tunnel with name already exists` issue.

As a suggestion:
Maybe there is a way to test the plugin within the release pipeline before the new version is published.

@brenner-tobias Thanks a lot for the quick response.

**Comment by SunsetGolfer** [comment]
v4.1.4 works fine for :+1:

Thanks to @brenner-tobias for the quick fix.

**Comment by nikoxley** [comment]
Yes confirmed working here too, many thanks for the fix and well done!

**Comment by Benne007** [comment]
v4..1.4 works good for me !
Tahnks @brenner-tobias for the quick fix. :-)

**Comment by elcajon** [comment]
> @elcajon are we sure this was fixed upstream?

I suspect due to the lack of the original Cloudflared build for amd64 something is skewed with the version. I would skip the version for the add-on and update again from the next release. According to the changelog we don't miss any major new features.
