### ISSUE TITLE
Add-On Metrics Not Exposed

### ISSUE THREAD

**Issue by xXAzazelXx** [brenner-tobias/addon-cloudflared#725]
### The problem

Hey Guys!

Great work on the add-on!

Unless I'm doing something wrong it looks like the add-on runs in bridge mode and does not map the metrics port so they are no accessible at all.

Is it possible to please have a look?

```
2024-10-25T13:19:41Z INF Starting metrics server on [::]:36500/metrics

sudo docker inspect ddcbe1fdee91 --format='{{.HostConfig.NetworkMode}}'
bridge
```

### What version of Cloudflared has the issue?

2024.10.0

### What was the last working version of Cloudflared?

2024.10.0

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

locally from SSHing to HA

curl http://127.0.0.1:36500/metrics

curl: (7) Failed to connect to 127.0.0.1 port 36500 after 0 ms: Could not connect to serve

**Comment by brenner-tobias** [comment]
Thanks for raising. You are right, currently the metrics server port is not exposed.
I just created a PR (#729) exposing the metrics server port.

**Comment by brenner-tobias** [comment]
I just released [v5.2.0](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v5.2.0) which includes the exposed metrics port that can be configured in the configuration in the network section.
Let me know if there are any issues.

**Comment by xXAzazelXx** [comment]
Thank you for having a look.
So is there anything i need to now enable in the configuration?


The documentation states that the metrics option is the default and I am still unable to see the exposed ports sorry
```

➜  ~ docker ps
CONTAINER ID   IMAGE                                                                 COMMAND                  CREATED          STATUS                  PORTS                                                                                                                                                                                                                                       NAMES
bddb71661d95   ghcr.io/brenner-tobias/cloudflared/amd64:5.2.0                        "/init"                  37 seconds ago   Up 36 seconds                           
```

**Comment by brenner-tobias** [comment]
Yes, you have to go to the add-on configuration page, scroll down to the network section and add any port there, that you want to map to the metrics server in the container running on 36500/tcp
If you do not have any specific requirements port-wise I suggest to simply add 36500 there as well as I did in the following screenshot:

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/ee0545bb-5d4d-4603-9702-c3d0980dc382">

**Comment by xXAzazelXx** [comment]
i see, works perfectly now! 
thank you!
